services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mark254_commerce
      MARIADB_USER: mark254
      MARIADB_PASSWORD: mark254_dev_pw
      MARIADB_ROOT_PASSWORD: change-me-root-pw
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
